version: '3'
services:
  slackboit:
    container_name: slackboit
    image: davonbarnette/slackboit
    volumes:
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - ./env/prod.env
    environment:
      - DB_HOST=slackboit_postgres
      - DB_SEQUELIZE_DIALECT=postgres
  postgres:
    container_name: slackboit_postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./env/postgres.prod.env
  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    env_file:
      - ./env/watchtower.prod.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup

