pre_build:
  commands:
    - echo Logging in to Docker Hub...
    - docker login
build:
  commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t davonbarnette:slackboit .
    - docker tag davonbarnette:slackboit davonbarnette:slackboit
post_build:
  commands:
    - echo Build completed on `date`
    - echo Pushing the Docker image...
    - docker push davonbarnette:slackboit