const USERS_BY_ID = {
    LOGAB: 'U8PJGRTGE',
    DAN:'U8F1U7VRS',
    ANDY:'U8DJE663U',
    BRUTLE:'U8NK2RBT9',
    YEETUS:'U9ADFB6H1',
    JAMZ:'U8ELJLTHV',
    MEGHOIT:'UL4TKUJG3',
    CHINNY:'UDKRCNYUU',
    COITIUS_THE_NOISTIUS:'UL6FD65TM',
    SLACKBOIT:'BGSDMPM42',
};

module.exports = USERS_BY_ID;